name: build

on: [push]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v1
            - name: Compile Nginx
              run: |
                sudo bash -ex ${GITHUB_WORKSPACE}/build.sh
                sudo mkdir -p .debpkg/usr/sbin .debpkg/etc/ .debpkg/var/cache/nginx .debpkg/var/log/nginx .debpkg/usr/lib/nginx/modules .debpkg/var/lib/nginx
                sudo cp /usr/sbin/nginx .debpkg/usr/sbin
                sudo cp -r /etc/nginx .debpkg/etc/nginx
                sudo mkdir -p .debpkg/lib/systemd/system/
                sudo cp /lib/systemd/system/nginx.service .debpkg/lib/systemd/system/nginx.service

            - uses: jiro4989/build-deb-action@v2
              id: debbuild
              with:
                package: nginx
                package_root: .debpkg
                maintainer: Longsight
                version: 1.0.0
                arch: 'amd64'
                desc: 'Nginx with sticky session support.'

            - uses: actions/upload-artifact@v3
              with:
                name: ${{ steps.debbuild.outputs.file_name }}
                path: ${{ steps.debbuild.outputs.file_name }}
