name: build

on: [push]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v1
            - name: Compile Nginx
              run: |
                sudo bash -ex ${GITHUB_WORKSPACE}/build.sh
                sudo mkdir -p .debpkg/usr/sbin .debpkg/etc/nginx .debpkg/var/cache/nginx .debpkg/var/log/nginx
                sudo cp /usr/sbin/nginx .debpkg/usr/sbin

            - uses: jiro4989/build-deb-action@v2
              with:
                package: nginx
                package_root: .debpkg
                maintainer: Longsight
                version: ${{ github.ref }} # refs/tags/v*.*.*
                arch: 'amd64'
                desc: 'Nginx with sticky session support.'
